name: Linters and Tests
on:
  push:
    branches:
      - main
  pull_request:
permissions:
    contents: write
    pull-requests: write
    repository-projects: write

jobs:
  main:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      actions: 'read'
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - uses: nrwl/nx-set-shas@v3

      - uses: akhilmhdh/contributors-readme-action@v2.3.6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - run: npm ci

      - run: npm run lint:js
      - run: npm run lint:syncpack
